FROM registry.access.redhat.com/ubi9/ubi-minimal

ENV LC_ALL C.UTF-8

USER root

RUN microdnf -y install dnsmasq
RUN rm -rf /var/cache/yum

EXPOSE 67/udp

ENTRYPOINT ["/bin/sh"]
CMD ["-c", "/usr/sbin/dnsmasq --log-facility=- --log-dhcp --log-async=0 -d"]