FROM ubi9-minimal

USER 0

RUN microdnf -y install reposync subscription-manager
RUN rm -rf /var/cache/yum

COPY sync-repo.sh /opt/sync-repo.sh
RUN chmod +x /opt/sync-repo.sh

VOLUME /workdir

ENTRYPOINT ["/bin/bash"]
CMD ["/opt/sync-repo.sh"]