{{ if .Values.dns }}
{{ if not .Values.dns.hostNetwork }}
---
apiVersion: v1
kind: Service
metadata:
  name: dns-service
spec:
  selector:
    app.kubernetes.io/name: dns
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
{{ end }}
{{ end }}