{{ if .Values.customerPortalDownloads }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: portal-downloads-ss-{{ $.Release.Name }}
  labels:
    app.kubernetes.io/name: portal-downloads-ss-{{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: portal-downloads
    app.kubernetes.io/part-of: bootstrap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: portal-downloads-{{ $.Release.Name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/part-of: bootstrap
  serviceName: portal-downloads-service
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portal-downloads-{{ $.Release.Name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/part-of: bootstrap
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: bootstrap-service-account
      containers:
        - name: portal-downloads
          image: registry.redhat.io/rhel9/httpd-24:latest
          ports:
            - containerPort: 8080
              name: port-8080
          volumeMounts:
            - name: portal-downloads-data
              mountPath: /var/www/html
      initContainers:
        - name: download-from-portal
          image: quay.io/jswanson/portal-download:1.0.3
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: portal-downloads-data
              mountPath: /workdir
            - name: customer-portal-downloads
              mountPath: /tmp/downloads.yaml
              subPath: downloads.yaml
              readOnly: true
          env:
            - name: DOWNLOADS
              value: /tmp/downloads.yaml
            - name: OFFLINE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: portal-downloads-offline-token-secret
                  key: offline_token
      volumes:
        - name: portal-downloads-data
          persistentVolumeClaim:
            claimName: portal-downloads-{{ $.Release.Name }}-pvc
        - name: customer-portal-downloads
          configMap:
            name: customer-portal-downloads-cm
{{ end }}
