{{ if .Values.customerPortalDownloads }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-portal-downloads-cm
data: 
  downloads.yaml: |
    ---
    {{- range .Values.customerPortalDownloads.downloads }}
    - name: {{ .name }}
      sha256: {{ .sha256 }}
    {{- end }}
{{ end }}