{{ if .Values.customerPortalDownloads }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-downloads-{{ $.Release.Name }}-pvc
  labels:
    app.kubernetes.io/name: portal-downloads-{{ $.Release.Name }}-pvc
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: bootstrap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  {{ if $.Values.storageClass }}
  storageClassName: {{ $.Values.storageClass }}
  {{ end }}
{{ end }}