{{ if .Values.ocMirror }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-{{ .Release.Name }}-pvc
  labels:
    app.kubernetes.io/name: registry-{{ .Release.Name }}-pvc
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: bootstrap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ocMirror.registryPvc.size | default "30Gi" }}
  {{ if .Values.ocMirror.registryPvc.storageClass }}
  storageClassName: {{ .Values.ocMirror.registryPvc.storageClass }}
  {{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc-mirror-scratch-{{ .Release.Name }}-pvc
  labels:
    app.kubernetes.io/name: oc-mirror-scratch-{{ .Release.Name }}-pvc
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: bootstrap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ocMirror.scratchPvc.size | default "10Gi" }}
  {{ if .Values.ocMirror.scratchPvc.storageClass }}
  storageClassName: {{ .Values.ocMirror.scratchPvc.storageClass }}
  {{ end }}
{{ end }}