---

- name: Setup local connections via NetworkManager
  hosts:
    - all
  become: true
  pre_tasks:
    - name: Ensure vars are defined
      ansible.builtin.assert:
        that:
          - wan.interface is defined
          - dhcp.interface is defined
          - dhcp.router is defined
          - dhcp.dnsServer is defined
          - dns.forwardZone is defined
        fail_msg: "Be sure to include your values.yaml file as extra vars."
  tasks:
    - name: set wan link to external zone
      community.general.nmcli:
        conn_name: "{{ wan.interface }}"
        zone: external
        state: present
      notify:
        - restart_nm
    - name: add nm conn for workshop
      community.general.nmcli:
        conn_name: "lan"
        type: ethernet
        ifname: "{{ dhcp.interface }}"
        ip4:
          - "{{ dhcp.router }}/{{ dhcp.netmask }}"
        dns4:
          - "{{ dhcp.dnsServer }}"
        dns4_search:
          - "{{ dns.forwardZone }}"
        zone: trusted
        state: present
      notify:
        - restart_nm
    - name: Allow access to k8s api
      ansible.posix.firewalld:
        port: 6443/tcp
        zone: external
        permanent: true
        immediate: true
        state: enabled
  handlers:
    - name: restart NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted
      listen:
        - restart_nm
    - name: wait for device to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300
      listen:
        - restart_nm